steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - --file
          - Assistant/browser-worker/Dockerfile
          - --tag
          - ${_IMAGE}
          - .
images:
    - ${_IMAGE}
