const { createLiveProgress, toolProgress, backgroundProgress } = require('./assistantLiveProgress')

beforeEach(() => jest.useFakeTimers())
afterEach(() => jest.useRealTimers())

test('coalesces stages, leaves quick requests quiet and spaces unchanged waits further apart', () => {
    const publish = jest.fn()
    const progress = createLiveProgress({ publish })
    const tick = () => progress.tick({ active: true, lastSpeechAt: 0 })
    jest.advanceTimersByTime(7000)
    progress.update('Searching tasks')
    expect(tick()).toBe(false)
    progress.update('Checking notes')
    jest.advanceTimersByTime(1000)
    expect(tick()).toBe(true)
    expect(publish.mock.calls).toEqual([['Checking notes']])
    jest.advanceTimersByTime(44000)
    expect(tick()).toBe(false)
    jest.advanceTimersByTime(1000)
    expect(tick()).toBe(true)
    progress.update('Reviewing results')
    jest.advanceTimersByTime(19000)
    expect(tick()).toBe(false)
    jest.advanceTimersByTime(1000)
    expect(tick()).toBe(true)
})

test('waits for a conversational pause and stops immediately on completion', () => {
    const publish = jest.fn()
    const progress = createLiveProgress({ publish })
    jest.advanceTimersByTime(9000)
    expect(progress.tick({ active: false, lastSpeechAt: 0 })).toBe(false)
    const speech = Date.now()
    expect(progress.tick({ active: true, lastSpeechAt: speech })).toBe(false)
    jest.advanceTimersByTime(4000)
    expect(progress.tick({ active: true, lastSpeechAt: speech })).toBe(true)
    progress.stop()
    progress.update('Stale tool result')
    jest.advanceTimersByTime(60000)
    expect(progress.tick({ active: true, lastSpeechAt: 0 })).toBe(false)
    expect(publish).toHaveBeenCalledTimes(1)
})

test('uses existing activity labels without arguments, tool identifiers or invented completion', () => {
    expect(toolProgress('web_search')).toContain('Searching the web')
    expect(toolProgress('create_task')).toContain('Creating a task')
    expect(toolProgress('unknown_private_tool')).toBe('I am still working on your request.')
    expect(backgroundProgress({ status: 'cancel_requested' })).toEqual({
        content: expect.stringContaining('not confirmed'),
        terminal: false,
    })
    expect(backgroundProgress({ status: 'completed' }).terminal).toBe(true)
    expect(backgroundProgress({ status: 'awaiting_user' }).content).toContain('needs your input')
    expect(backgroundProgress({ status: 'unknown', output: 'private' })).toBeNull()
})
