const { createLiveAnswerDelivery, splitLiveAnswer } = require('./assistantLiveAnswerDelivery')
beforeEach(() => jest.useFakeTimers())
afterEach(() => jest.useRealTimers())
const setup = result => {
    const append = jest.fn(),
        record = jest.fn(),
        finish = jest.fn(),
        supersede = jest.fn()
    const delivery = createLiveAnswerDelivery({ result, delegationId: 'd1', append, record, finish, supersede })
    const tick = (lastSpeechAt = 0) => delivery.tick({ active: true, lastSpeechAt })
    const acknowledge = type =>
        append.mock.calls
            .filter(call => call[0] === type)
            .forEach(call => delivery.acknowledge({ type: `${type}ed`, client_event_id: call[3] }))
    return { delivery, tick, append, record, finish, supersede, acknowledge }
}
test('preserves the whole multibyte answer, waits for context acceptance and a pause before speech', () => {
    const text = 'Eine Antwort. 界'.repeat(120)
    const chunks = splitLiveAnswer(text)
    expect(chunks.join('')).toBe(text)
    const s = setup(text)
    s.tick()
    expect(s.append.mock.calls.every(call => Buffer.byteLength(call[1], 'utf8') < 480)).toBe(true)
    expect(s.append.mock.calls.filter(call => call[0] === 'session.commentary.append')).toHaveLength(0)
    s.acknowledge('session.thinking.append')
    s.tick(Date.now())
    expect(s.append.mock.calls.filter(call => call[0] === 'session.commentary.append')).toHaveLength(0)
    jest.advanceTimersByTime(1600)
    s.tick()
    expect(s.append.mock.calls.filter(call => call[0] === 'session.commentary.append')).toHaveLength(1)
    expect(s.finish).not.toHaveBeenCalled()
    s.acknowledge('session.commentary.append')
    expect(s.finish).toHaveBeenCalledTimes(1)
    expect(s.record).toHaveBeenCalledWith(expect.objectContaining({ deliveryStatus: 'answer_acknowledged' }))
    expect(s.record.mock.calls.some(([data]) => data.outputObservedAfterAnswerAt)).toBe(false)
    expect(s.delivery.awaitingSpeech).toBe(true)
})
test('waits for every context part and ignores unrelated or wrong-type acknowledgments', () => {
    const s = setup('A'.repeat(900))
    s.tick()
    const parts = s.append.mock.calls
    const ack = (index, type = 'session.thinking.appended') =>
        s.delivery.acknowledge({ type, client_event_id: parts[index][3] })
    ack(0)
    ack(1)
    ack(2, 'session.commentary.appended')
    s.delivery.acknowledge({ type: 'session.thinking.appended', client_event_id: 'unrelated' })
    s.tick()
    expect(s.append.mock.calls.some(call => call[0] === 'session.commentary.append')).toBe(false)
    ack(2)
    s.tick()
    expect(s.append.mock.calls.filter(call => call[0] === 'session.commentary.append')).toHaveLength(1)
})
test('retries quiet context once, but never blindly repeats an unacknowledged spoken answer', () => {
    const s = setup('Verified answer')
    s.tick()
    jest.advanceTimersByTime(6100)
    s.tick()
    expect(s.append.mock.calls.filter(call => call[0] === 'session.thinking.append')).toHaveLength(2)
    s.acknowledge('session.thinking.append')
    s.tick()
    jest.advanceTimersByTime(6100)
    s.tick()
    expect(s.append.mock.calls.filter(call => call[0] === 'session.commentary.append')).toHaveLength(1)
    expect(s.record).toHaveBeenCalledWith(
        expect.objectContaining({ deliveryStatus: 'ack_timeout', deliveryTimeoutStage: 'answer' })
    )
})
test('a correction before handoff cancels delivery and reconciles the new request', () => {
    const s = setup('Friday result')
    s.tick()
    s.delivery.cancel()
    s.acknowledge('session.thinking.append')
    s.tick()
    expect(s.supersede).toHaveBeenCalledTimes(1)
    expect(s.append.mock.calls.some(call => call[0] === 'session.commentary.append')).toBe(false)
})
test.each([true, false])('recovery distinguishes observed output from acceptance: output=%s', output => {
    const s = setup('Ready')
    s.tick()
    s.acknowledge('session.thinking.append')
    s.tick()
    s.acknowledge('session.commentary.append')
    if (output) s.delivery.observeOutput()
    jest.advanceTimersByTime(11000)
    s.tick()
    expect(s.record.mock.calls.some(([data]) => data.deliveryStatus === 'speech_unobserved')).toBe(!output)
    expect(s.delivery.awaitingSpeech).toBe(false)
    expect(s.append.mock.calls.filter(call => call[0] === 'session.commentary.append')).toHaveLength(1)
})

test('records a disconnected handoff and ignores late acknowledgments', () => {
    const s = setup('Saved result')
    s.tick()
    s.delivery.close()
    s.acknowledge('session.thinking.append')
    jest.advanceTimersByTime(15000)
    s.tick()
    expect(s.record).toHaveBeenCalledWith(
        expect.objectContaining({ deliveryStatus: 'call_closed_before_ack', deliveryCloseStage: 'context' })
    )
    expect(s.append.mock.calls.some(call => call[0] === 'session.commentary.append')).toBe(false)
    expect(s.supersede).not.toHaveBeenCalled()
})
